# Uncomment the line if you want fastlane to automatically update itself
update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  lane :increment do
    path = '../buildSrc/src/main/kotlin/AppConfig.kt'
    reCode = /const\s+val\s+versionCode\s+=\s+(\d+)/
    reName = /const\s+val\s+versionName\s+=\s+"(?:\d+\.)+\K\d+/

    s = File.read(path)
    versionCode = s[reCode, 1].to_i
    versionNamePath = s[reName, 1].to_i
    s[reCode, 1] = (versionCode + 1).to_s
    s[reName, 1] = (versionNamePath + 1).to_s

    f = File.new(path, 'w')
    f.write(s)
    f.close
  end

  lane :gitpush do
    git_add
    git_commit(path: "*", message: "Version Update")
    push_to_git_remote
  end

  desc "Submit a new Release Build to Github Semantic Release"
  lane :release do
    gradle(task: "clean bundleRelease")
  end

  desc "Submit a new Release Build to Github Semantic Release"
  lane :deploy do
    gradle(task: "clean bundleRelease")
    upload_to_play_store
  end
end
