package com.adiliqbal.finize.ui.design

import androidx.compose.ui.graphics.Color

internal val md_theme_light_primary = Color(0xFF005AC1)
internal val md_theme_light_onPrimary = Color(0xFFFFFFFF)
internal val md_theme_light_primaryContainer = Color(0xFFD8E2FF)
internal val md_theme_light_onPrimaryContainer = Color(0xFF001A41)
internal val md_theme_light_secondary = Color(0xFF006C47)
internal val md_theme_light_onSecondary = Color(0xFFFFFFFF)
internal val md_theme_light_secondaryContainer = Color(0xFF8EF7C0)
internal val md_theme_light_onSecondaryContainer = Color(0xFF002112)
internal val md_theme_light_tertiary = Color(0xFF005AC1)
internal val md_theme_light_onTertiary = Color(0xFFFFFFFF)
internal val md_theme_light_tertiaryContainer = Color(0xFFD8E2FF)
internal val md_theme_light_onTertiaryContainer = Color(0xFF001A41)
internal val md_theme_light_error = Color(0xFFBA1A1A)
internal val md_theme_light_errorContainer = Color(0xFFFFDAD6)
internal val md_theme_light_onError = Color(0xFFFFFFFF)
internal val md_theme_light_onErrorContainer = Color(0xFF410002)
internal val md_theme_light_background = Color(0xFFF8FDFF)
internal val md_theme_light_onBackground = Color(0xFF001F25)
internal val md_theme_light_surface = Color(0xFFF8FDFF)
internal val md_theme_light_onSurface = Color(0xFF001F25)
internal val md_theme_light_surfaceVariant = Color(0xFFE1E2EC)
internal val md_theme_light_onSurfaceVariant = Color(0xFF44474F)
internal val md_theme_light_outline = Color(0xFF74777F)
internal val md_theme_light_inverseOnSurface = Color(0xFFD6F6FF)
internal val md_theme_light_inverseSurface = Color(0xFF00363F)
internal val md_theme_light_inversePrimary = Color(0xFFADC6FF)
internal val md_theme_light_shadow = Color(0xFF000000)
internal val md_theme_light_surfaceTint = Color(0xFF005AC1)
internal val md_theme_light_outlineVariant = Color(0xFFC4C6D0)
internal val md_theme_light_scrim = Color(0xFF000000)

internal val md_theme_dark_primary = Color(0xFFADC6FF)
internal val md_theme_dark_onPrimary = Color(0xFF002E69)
internal val md_theme_dark_primaryContainer = Color(0xFF004494)
internal val md_theme_dark_onPrimaryContainer = Color(0xFFD8E2FF)
internal val md_theme_dark_secondary = Color(0xFF72DAA6)
internal val md_theme_dark_onSecondary = Color(0xFF003823)
internal val md_theme_dark_secondaryContainer = Color(0xFF005234)
internal val md_theme_dark_onSecondaryContainer = Color(0xFF8EF7C0)
internal val md_theme_dark_tertiary = Color(0xFFADC6FF)
internal val md_theme_dark_onTertiary = Color(0xFF002E69)
internal val md_theme_dark_tertiaryContainer = Color(0xFF004494)
internal val md_theme_dark_onTertiaryContainer = Color(0xFFD8E2FF)
internal val md_theme_dark_error = Color(0xFFFFB4AB)
internal val md_theme_dark_errorContainer = Color(0xFF93000A)
internal val md_theme_dark_onError = Color(0xFF690005)
internal val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
internal val md_theme_dark_background = Color(0xFF001F25)
internal val md_theme_dark_onBackground = Color(0xFFA6EEFF)
internal val md_theme_dark_surface = Color(0xFF001F25)
internal val md_theme_dark_onSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_surfaceVariant = Color(0xFF44474F)
internal val md_theme_dark_onSurfaceVariant = Color(0xFFC4C6D0)
internal val md_theme_dark_outline = Color(0xFF8E9099)
internal val md_theme_dark_inverseOnSurface = Color(0xFF001F25)
internal val md_theme_dark_inverseSurface = Color(0xFFA6EEFF)
internal val md_theme_dark_inversePrimary = Color(0xFF005AC1)
internal val md_theme_dark_shadow = Color(0xFF000000)
internal val md_theme_dark_surfaceTint = Color(0xFFADC6FF)
internal val md_theme_dark_outlineVariant = Color(0xFF44474F)
internal val md_theme_dark_scrim = Color(0xFF000000)


internal val seed = Color(0xFF4285F4)

internal val Success = Color(0xFF00C47E)
internal val light_Success = Color(0xFF006D44)
internal val light_onSuccess = Color(0xFFFFFFFF)
internal val light_SuccessContainer = Color(0xFF63FDB1)
internal val light_onSuccessContainer = Color(0xFF002111)
internal val dark_Success = Color(0xFF40E097)
internal val dark_onSuccess = Color(0xFF003921)
internal val dark_SuccessContainer = Color(0xFF005232)
internal val dark_onSuccessContainer = Color(0xFF63FDB1)
