name: Distribute

# TODO: Fix for develop
#on:
#  push:
#    branches:
#      #      - '*'
#      #      - '**'
#      #      - '*/*'

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'

      # Cache
      - name: Cache Ruby - Bundler
        uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Cache Gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}
      - name: Cache Gradle Wrapper
        uses: actions/cache@v1
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      # Setup
      - name: Grant Permission to Execute
        run: chmod +x gradlew
      - name: Install bundle
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      # Secrets
      - name: Create .properties file
        run: |
          echo "$PROD_PROPERTIES_JSON" > production.properties.b64
          base64 -d -i production.properties.b64 > production.properties
        env:
          PROD_PROPERTIES_JSON: ${{ secrets.PROD_PROPERTIES_JSON }}

      # Actions
      - name: Unit tests
        run: bundle exec fastlane test